import { MayRLabsAuthError } from "../errors";
import type {
  AuthErrorPayload,
  AuthUserPayload,
  ClientConfig,
  ClientConfigInput,
} from "../types";
import { BaseAuthSetup } from "./base";
import { CLIENT_SESSION_KEY, ISSUER } from "./constants";

const DEFAULTS = {
  redirects: { error: "/login", success: "/dashboard" },
  session: { key: CLIENT_SESSION_KEY },
};

export class ClientAuthSetup extends BaseAuthSetup<ClientConfig> {
  constructor(input: ClientConfigInput) {
    super({
      ...input,
      issuer: input.issuer || ISSUER,
      redirects: { ...DEFAULTS.redirects, ...input.redirects },
      session: { ...DEFAULTS.session, ...input.session },
    });
  }

  /**
   * Constructs the URL to the centralized login page.
   * Includes the `appId` search parameter with the configured clientId.
   *
   * @returns The fully qualified login URL as a string.
   */
  getLoginUrl(): string {
    const url = new URL(`${this.config.accountUrl}/login`);
    url.searchParams.set("appId", this.config.clientId);

    return url.toString();
  }

  /**
   * Authenticates as a machine/service using the Client ID and Secret.
   * Performs a request to the configured accountUrl.
   *
   * @returns A promise that resolves to the machine authentication token.
   *
   * @throws {MayRLabsAuthError} If authentication fails or network error occurs.
   */
  async authenticateMachine(): Promise<string> {
    try {
      const response = await fetch(
        `${this.config.accountUrl}/api/auth/service`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            clientId: this.config.clientId,
            clientSecret: this.config.clientSecret,
          }),
        },
      );

      if (!response.ok) {
        const errorData = (await response.json().catch(() => ({}))) as {
          message?: string;
          code?: string;
        };

        throw new MayRLabsAuthError(
          errorData.message || "Failed to authenticate machine",
          errorData.code || "MACHINE_AUTH_FAILED",
        );
      }

      const data = (await response.json()) as { token: string };

      return data.token;
    } catch (error) {
      if (error instanceof MayRLabsAuthError) throw error;

      throw new MayRLabsAuthError(
        `Machine authentication network error: ${error instanceof Error ? error.message : "Unknown error"}`,
        "MACHINE_AUTH_NETWORK_ERROR",
      );
    }
  }

  /**
   * Verifies an authentication token generated by the Issuer.
   * Defaults the expected audience to this client's `clientId` if not provided.
   *
   * @param token The JWT string to verify.
   * @param audience Optional audience to override the default.
   *
   * @returns The authenticated user payload on success, or null.
   */
  async verifyAuthToken(
    token: string,
    audience?: string,
  ): Promise<AuthUserPayload | null> {
    return super.verifyAuthToken(token, audience || this.config.clientId);
  }

  /**
   * Verifies an error token indicating an authentication failure.
   * Defaults the expected audience to this client's `clientId` if not provided.
   *
   * @param token The JWT string.
   * @param audience Optional audience to override the default.
   *
   * @returns The error payload containing code and message, or null.
   */
  async verifyErrorToken(
    token: string,
    audience?: string,
  ): Promise<AuthErrorPayload | null> {
    return super.verifyErrorToken(token, audience || this.config.clientId);
  }
}
