import type { JWTPayload } from "jose";

/**
 * Payload structure for authenticated users representing their identity and claims.
 * Aligned with the MyR Labs Account Center user schema.
 */
export interface AuthUserPayload extends JWTPayload {
  /**
   * The unique identifier for the user.
   */
  id: string;
  /**
   * The user's primary email address.
   */
  email: string;
  /**
   * The user's list of assigned roles.
   */
  roles: string[];
  /**
   * The user's first name.
   */
  firstName: string | null;
  /**
   * The user's last name.
   */
  lastName: string | null;
  /**
   * The user's custom username.
   */
  username: string | null;
  /**
   * The URL to the user's profile image.
   */
  avatarUrl: string;
}

/**
 * Payload structure for machine-to-machine authentications.
 */
export interface AuthMachinePayload extends JWTPayload {
  sub: string;
  type: "machine";
}

/**
 * Payload structure representing authentication errors generated by the Issuer.
 */
export interface AuthErrorPayload extends JWTPayload {
  code: string;
  message: string;
}

/**
 * Core configuration required for Issuer authentication utilities.
 */
export interface IssuerConfig {
  privateKey: string;
  publicKey: string;
  issuer: string;
}

/**
 * Configuration input for creating an Issuer Auth setup.
 */
export interface IssuerConfigInput extends Omit<IssuerConfig, "issuer"> {
  /**
   * The issuer string indicating the origin of tokens (e.g. 'auth.mayrlabs.com').
   */
  issuer?: string;
}

/**
 * Core configuration required for Client authentication utilities.
 */
export interface ClientConfig {
  accountUrl: string;
  clientId: string;
  clientSecret: string;
  publicKey?: string;
  remotePublicKey?: boolean;
  issuer: string;
  redirects: { error: string; success: string };
  session: { key: string };
  events?: {
    onAuthSuccess?: (user: AuthUserPayload) => Promise<void> | void;
    onAuthFailure?: (error: AuthErrorPayload) => Promise<void> | void;
  };
}

/**
 * Configuration input for creating a Client Auth setup.
 */
export interface ClientConfigInput
  extends Omit<ClientConfig, "redirects" | "session" | "issuer"> {
  /**
   * The issuer string representing the expected token issuer.
   */
  issuer?: string;
  /**
   * Redirect paths after authentication callbacks.
   */
  redirects?: Partial<ClientConfig["redirects"]>;
  /**
   * Session cookie configurations.
   */
  session?: Partial<ClientConfig["session"]>;
}
