import type { JWTPayload } from "jose";

/**
 * Payload structure for authenticated users representing their identity and claims.
 */
export interface MayRLabsAuthUserPayload extends JWTPayload {
  userId: string;
  email: string;
  roles: string[];
  firstName?: string;
  lastName?: string;
}

/**
 * Payload structure for machine-to-machine authentications.
 */
export interface MayRLabsAuthMachinePayload extends JWTPayload {
  sub: string;
  type: "machine";
}

/**
 * Payload structure representing authentication errors generated by the Issuer.
 */
export interface MayRLabsAuthErrorPayload extends JWTPayload {
  code: string;
  message: string;
}

/**
 * Core configuration required for Issuer authentication utilities.
 */
export interface IssuerConfig {
  privateKey: string;
  publicKey: string;
  issuer: string;
}

/**
 * Configuration input for creating an Issuer Auth setup.
 */
export interface IssuerConfigInput extends Omit<IssuerConfig, "issuer"> {
  /**
   * The issuer string indicating the origin of tokens (e.g. 'auth.mayrlabs.com').
   */
  issuer?: string;
}

/**
 * Core configuration required for Client authentication utilities.
 */
export interface ClientConfig {
  accountUrl: string;
  clientId: string;
  clientSecret: string;
  publicKey?: string;
  remotePublicKey?: boolean;
  issuer: string;
  redirects: { error: string; success: string };
  session: { key: string };
}

/**
 * Configuration input for creating a Client Auth setup.
 */
export interface ClientConfigInput
  extends Omit<ClientConfig, "redirects" | "session" | "issuer"> {
  /**
   * The issuer string representing the expected token issuer.
   */
  issuer?: string;
  /**
   * Redirect paths after authentication callbacks.
   */
  redirects?: Partial<ClientConfig["redirects"]>;
  /**
   * Session cookie configurations.
   */
  session?: Partial<ClientConfig["session"]>;
}
